name: poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/svg/
      - assets/images/svg/logos/
      - assets/images/svg/pokemon_information/
      - assets/images/png/coaches/
      - assets/images/png/others/
      - assets/images/png/regions/
      - assets/icons/
      - assets/icons/png/theme/
      - assets/icons/png/notifications/
      - assets/icons/svg/
      - assets/icons/svg/bottom_menu/
      - assets/icons/svg/search_textfield/
      - assets/icons/svg/pokemons/elements/
      - assets/icons/svg/pokemons/elements_with_transparency/
      - assets/icons/svg/pokemon_informations/
      - assets/icons/svg/pokemons/favorite/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: normal

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 400

        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900

        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic



        

