Map<String, String> pokemonTypeTransparencyIcons = {
  "normal": 'assets/icons/svg/pokemons/elements_with_transparency/normal_element.svg',
  "fighting": 'assets/icons/svg/pokemons/elements_with_transparency/fighting_element.svg',
  "flying": 'assets/icons/svg/pokemons/elements_with_transparency/flying_element.svg',
  "poison": 'assets/icons/svg/pokemons/elements_with_transparency/poison_element.svg',
  "ground": 'assets/icons/svg/pokemons/elements_with_transparency/ground_element.svg',
  "rock": 'assets/icons/svg/pokemons/elements_with_transparency/rock_element.svg',
  "bug": 'assets/icons/svg/pokemons/elements_with_transparency/bug_element.svg',
  "ghost": 'assets/icons/svg/pokemons/elements_with_transparency/ghost_element.svg',
  "steel": 'assets/icons/svg/pokemons/elements_with_transparency/steel_element.svg',
  "fire": 'assets/icons/svg/pokemons/elements_with_transparency/fire_element.svg',
  "water": 'assets/icons/svg/pokemons/elements_with_transparency/water_element.svg',
  "grass": 'assets/icons/svg/pokemons/elements_with_transparency/grass_element.svg',
  "electric": 'assets/icons/svg/pokemons/elements_with_transparency/eletric_element.svg',
  "psychic": 'assets/icons/svg/pokemons/elements_with_transparency/psynic_element.svg',
  "ice": 'assets/icons/svg/pokemons/elements_with_transparency/ice_element.svg',
  "dragon": 'assets/icons/svg/pokemons/elements_with_transparency/dragon_element.svg',
  "dark": 'assets/icons/svg/pokemons/elements_with_transparency/dark_element.svg',
  "fairy": 'assets/icons/svg/pokemons/elements_with_transparency/fairy_element.svg',
};
