const Map<String, String> pokemonTypeIcons = {
  "normal": 'assets/icons/svg/pokemons/elements/normal_element.svg',
  "fighting": 'assets/icons/svg/pokemons/elements/fighting_element.svg',
  "flying": 'assets/icons/svg/pokemons/elements/flying_element.svg',
  "poison": 'assets/icons/svg/pokemons/elements/poison_element.svg',
  "ground": 'assets/icons/svg/pokemons/elements/ground_element.svg',
  "rock": 'assets/icons/svg/pokemons/elements/rock_element.svg',
  "bug": 'assets/icons/svg/pokemons/elements/bug_element.svg',
  "ghost": 'assets/icons/svg/pokemons/elements/ghost_element.svg',
  "steel": 'assets/icons/svg/pokemons/elements/steel_element.svg',
  "fire": 'assets/icons/svg/pokemons/elements/fire_element.svg',
  "water": 'assets/icons/svg/pokemons/elements/water_element.svg',
  "grass": 'assets/icons/svg/pokemons/elements/grass_element.svg',
  "electric": 'assets/icons/svg/pokemons/elements/eletric_element.svg',
  "psychic": 'assets/icons/svg/pokemons/elements/psynic_element.svg',
  "ice": 'assets/icons/svg/pokemons/elements/ice_element.svg',
  "dragon": 'assets/icons/svg/pokemons/elements/dragon_element.svg',
  "dark": 'assets/icons/svg/pokemons/elements/dark_element.svg',
  "fairy": 'assets/icons/svg/pokemons/elements/fairy_element.svg',
};
