Map<String, String> typeIconsTransparencyPath = {
  "Normal": 'assets/icons/svg/pokemons/elements_with_transparency/normal_element.svg',
  "Lutador": 'assets/icons/svg/pokemons/elements_with_transparency/fighting_element.svg',
  "Voador": 'assets/icons/svg/pokemons/elements_with_transparency/flying_element.svg',
  "Venenoso": 'assets/icons/svg/pokemons/elements_with_transparency/poison_element.svg',
  "Terrestre": 'assets/icons/svg/pokemons/elements_with_transparency/ground_element.svg',
  "Pedra": 'assets/icons/svg/pokemons/elements_with_transparency/rock_element.svg',
  "Inseto": 'assets/icons/svg/pokemons/elements_with_transparency/bug_element.svg',
  "Fantasma": 'assets/icons/svg/pokemons/elements_with_transparency/ghost_element.svg',
  "Aço": 'assets/icons/svg/pokemons/elements_with_transparency/steel_element.svg',
  "Fogo": 'assets/icons/svg/pokemons/elements_with_transparency/fire_element.svg',
  "Água": 'assets/icons/svg/pokemons/elements_with_transparency/water_element.svg',
  "Grama": 'assets/icons/svg/pokemons/elements_with_transparency/grass_element.svg',
  "Elétrico": 'assets/icons/svg/pokemons/elements_with_transparency/eletric_element.svg',
  "Psíquico": 'assets/icons/svg/pokemons/elements_with_transparency/psynic_element.svg',
  "Gelo": 'assets/icons/svg/pokemons/elements_with_transparency/ice_element.svg',
  "Dragão": 'assets/icons/svg/pokemons/elements_with_transparency/dragon_element.svg',
  "Sombrio": 'assets/icons/svg/pokemons/elements_with_transparency/dark_element.svg',
  "Fada": 'assets/icons/svg/pokemons/elements_with_transparency/fairy_element.svg',
};
