Map<String, String> typeIconsPath = {
  "Normal": 'assets/icons/svg/pokemons/elements/normal_element.svg',
  "Lutador": 'assets/icons/svg/pokemons/elements/fighting_element.svg',
  "Voador": 'assets/icons/svg/pokemons/elements/flying_element.svg',
  "Venenoso": 'assets/icons/svg/pokemons/elements/poison_element.svg',
  "Terrestre": 'assets/icons/svg/pokemons/elements/ground_element.svg',
  "Pedra": 'assets/icons/svg/pokemons/elements/rock_element.svg',
  "Inseto": 'assets/icons/svg/pokemons/elements/bug_element.svg',
  "Fantasma": 'assets/icons/svg/pokemons/elements/ghost_element.svg',
  "Aço": 'assets/icons/svg/pokemons/elements/steel_element.svg',
  "Fogo": 'assets/icons/svg/pokemons/elements/fire_element.svg',
  "Água": 'assets/icons/svg/pokemons/elements/water_element.svg',
  "Grama": 'assets/icons/svg/pokemons/elements/grass_element.svg',
  "Elétrico": 'assets/icons/svg/pokemons/elements/eletric_element.svg',
  "Psíquico": 'assets/icons/svg/pokemons/elements/psynic_element.svg',
  "Gelo": 'assets/icons/svg/pokemons/elements/ice_element.svg',
  "Dragão": 'assets/icons/svg/pokemons/elements/dragon_element.svg',
  "Sombrio": 'assets/icons/svg/pokemons/elements/dark_element.svg',
  "Fada": 'assets/icons/svg/pokemons/elements/fairy_element.svg',
};
